### ISSUE TITLE
Edit not working with specified SHEET_FILE

### ISSUE THREAD

**Issue by Henrik-Wik** [dribnif/tt#26]
After specifying my SHEET_FILE I now have that as the json database, but  when running tt edit it opens a yaml file in AppData > Local > Temp. Shouldn't it open my json file?
![image](https://github.com/user-attachments/assets/0c63f783-98fd-46ec-afe5-bb0b0ad967c6)

**Comment by dribnif** [comment]
Hey @Henrik-Wik , tt behaves as expected. This is also documented here: [https://github.com/dribnif/tt#change-entries](https://github.com/dribnif/tt#change-entries)

`This will open your time entry DB using the specified editor in the handy YAML format. Once you save your changes and exit the file, the changes will be persisted back into your SHEET_FILE.`

The reason for this is to protect your main db file from direct human contact, in order to reduce the chance of corruption.

**Comment by Henrik-Wik** [comment]
Ah, I see. Thanks for the clarification! 👍
